* Notes diverses
  
** TODO [3/8]
 * [X] Génération du scale-free selon un vrai algorithme
 * [X] Vérifier le comportement de testsf :: est-ce bien un noeud au moins qui est voisin (pas plus ?)
 * [-] Passer en bidirectionnel :: plus en accord avec la littérature
   + [X] Scale-free
   + [ ] Homogène, algorithme plus compliqué
   + [X] En étoile
 * [-] Graphes :: pour testsf au début. Il faudrait unifier tout ça aussi !
   + [-] Unifier les graphes :: ajouter les fonctions en rapport dans le module graphe
     - [ ] Pour un réseau homogène :: utiliser networkx
     - [X] Pour un scale-free
   + [X] Ajouter une option pour afficher les graphes correspondants à chaque itération
   + [X] Afficher des graphes avec en abscisse degré total des attaquants, en ordonnée le nombre d'attaquants CLOCK: [2017-05-14 dim. 14:35]--[2017-05-14 dim. 15:00] =>  0:25
 * [X] Optimiser les fonctions ::
 * [-] Présentation :: voir Notes bis [2/3]
   + [X] Français
   + [X] Graphes en LaTeX
   + [-] Génération des résultats
   + [ ] Diverses choses
 * [-] Parsing :: faire un vrai parsing des arguments
   + [-] Pour testsf. La suite viendra après ce qui est plus important.
   + [ ] Pour un réseau homogène
   + [ ] Afficher l'aide correctement
 * [ ] Propagation avec choix des agents (de conserver certaines informations ou pas)
** A lire
 - The Law of The Few - Goyal

** Notes
 - attaques sur les liens
 - diffusion, contagion dans un réseau
 - le réseau créé, avec cette transmission, est un *arbre* !
 - représenter réseaux en LaTeX
 - pour avoir moins de problèmes de connexité (donc accélère la génération) : réseau multi-directionnel
 - agents hétérogènes (différents types, tendance *homophilique* : se connectent plutôt avec des agents du même type)
 - donc modifient la propagation
   
** Notes bis
 - Les motivations sont importantes !
 - Sommaire :
   + Faire disparaître le mot *homogène*, non défini pour le moment
 - Ne pas mettre la slide les objets du réseau :: dire «J'ai modélisé le réseau avec des objets Python.»
 - Les arêtes, tunnels sont des canaux de diffusion de l'information.
 - Ne pas mettre le slide «en étoile». De manière générale, enlever tout ce qui est présent «pour raisons historiques»
 - Homogène :: représentation avec LaTeX
 - Scale-free ::
   + faire disparaître le terme «random network», non défini.
   + Remplacer les images de graphes par des trucs LaTeX
   + Afficher un graphe abscisses : Degré total des attaquants, ordonnée : nombre d'attaquants
 - Variation du nombre de noeuds ::
   + afficher les courbes sur un même graphe (abscisse et ordonnées en %)
   + «semble tendre vers une exponentielle» :: *NON*, ne pas affirmer de choses sans fondements. Par contre, expliquer (formellement, ou avec des raisons fortes) pourquoi c'est croissant : *OUI* 
   + de même, dire que la dérivée seconde est décroissante : les attaquants tentent de contaminer des agents déjà infectés.
 - Variation du nombre d'arêtes ::
   + Pour le second graphe, la première partie n'est a priori pas de pente plus élevé
 - Conclusion :: revenir un peu sur les motivations
 - Général ::
   + Faire une moyenne sur un grand nombre de réseaux. Pour cela, optimiser
   + Pour les attaquants, ne pas prendre les p derniers/premiers noeuds, mais les tirer au hasard
   + Génération du scale-free :: implémenter l'algorithme de Albert-... (premier sur W)
   + Passer en bidirectionnel

** Notes ter
 * Motivations :
   + Parler de l'évolution récente (vingt ans) ::
     avant, banque, sécu... en intranet au mieux (assez sécurisé), maintenant sur le net (moins cher, moins safe)
 * Réseau en étoile :: comme le minitel
 * Scale-free :: à revoir : k^(-gamma) probabilité ? alors la somme n'est pas égale à 1. et 1^-gamma = 1...
   + Comprendre, d'après Barabasi-Albert, pourquoi le gamma intervient
 * Graphe somme degrés / nbr atks :: peu clair, à expliciter
